import QLTH.java.Student;
import QLTH.java.Class;
import QLTH.java.ClassModify;
import QLTH.java.ConnectionDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import QLTH.java.StudentModify;
import QLTH.java.Teacher;
import QLTH.java.TeacherModify;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author southmom16
 */
public class QLTH extends javax.swing.JFrame {
    DefaultTableModel tableModel1;
    DefaultTableModel tableModel2;
    DefaultTableModel tableModel3;


    
    List<Student> studentList = new ArrayList<>();
    List<Teacher> teacherList = new ArrayList<>();
    List<Class> classList = new ArrayList<>();


    /**
     * Creates new form QLTH
     */
    public QLTH() {
        initComponents();
        tableModel1 = (DefaultTableModel) tblStudent.getModel();
        tableModel2 = (DefaultTableModel) tblTeacher.getModel();
        tableModel3 = (DefaultTableModel) tblClass.getModel();


        
        showStudent();
        showTeacher();
        showClass();
        
        loadClassNameToCombobox();  
    }
    private void showStudent() {
        studentList = StudentModify.findAll();
        
        tableModel1.setRowCount(0);
        
        studentList.forEach((student) -> {
            tableModel1.addRow(new Object[] {student.getId(), 
                student.getName(), student.getAddress(), student.getEmail(), student.getPhoneNumber(), student.getNationality(), student.getClassName()});
        });
    }
    public void loadClassNameToCombobox(){
        Connection connection = ConnectionDB.openConnection();
        PreparedStatement statement = null;
        //Lay du lieu tu database do ra
        String sql = "SELECT * FROM Class";

        try {
             statement = connection.prepareStatement(sql);
            //lay du lieu tra ve
            ResultSet resultSet = statement.executeQuery();
            //resultset la con tro, tro vao du lieu tra ve trong cau sql
            cbxClassName.removeAllItems();
            while (resultSet.next()){
                cbxClassName.addItem(resultSet.getString("ClassName"));
            }
            resultSet.close();
            statement.close();
            ConnectionDB.closeConnection();
        } catch (SQLException ex) {
            if (statement != null){
                try{
                    statement.close();
                } catch (SQLException e) {
                    Logger.getLogger(ConnectionDB.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtClassName = new javax.swing.JTextField();
        btnAddClass = new javax.swing.JButton();
        btnDelClass = new javax.swing.JButton();
        btnFindClass = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClass = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTeacherID = new javax.swing.JTextField();
        txtTeacherName = new javax.swing.JTextField();
        txtTeacherAddress = new javax.swing.JTextField();
        txtTeacherEmail = new javax.swing.JTextField();
        txtTeacherPhoneNumber = new javax.swing.JTextField();
        txtTeacherNationality = new javax.swing.JTextField();
        txtTeacherSpecialization = new javax.swing.JTextField();
        btnAddTeacher = new javax.swing.JButton();
        btnEditTeacher = new javax.swing.JButton();
        btnDelTeacher = new javax.swing.JButton();
        btnFindTeacher = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTeacher = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        txtStudentName = new javax.swing.JTextField();
        txtStudentAddress = new javax.swing.JTextField();
        txtStudentEmail = new javax.swing.JTextField();
        txtStudentPhoneNumber = new javax.swing.JTextField();
        txtStudentNationality = new javax.swing.JTextField();
        cbxClassName = new javax.swing.JComboBox<>();
        btnAddStudent = new javax.swing.JButton();
        btnEditStudent = new javax.swing.JButton();
        btnDelStudent = new javax.swing.JButton();
        btnFindStudent = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School Manager");

        jPanel1.setPreferredSize(new java.awt.Dimension(584, 6500));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(652, 338));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Class Manager"));

        jLabel8.setText("Class Name");

        btnAddClass.setText("Add");
        btnAddClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClassActionPerformed(evt);
            }
        });

        btnDelClass.setText("Delete");
        btnDelClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelClassActionPerformed(evt);
            }
        });

        btnFindClass.setText("Find");
        btnFindClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(86, 86, 86)
                        .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAddClass)
                        .addGap(118, 118, 118)
                        .addComponent(btnDelClass)
                        .addGap(47, 47, 47)))
                .addGap(70, 70, 70)
                .addComponent(btnFindClass)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddClass)
                    .addComponent(btnDelClass)
                    .addComponent(btnFindClass))
                .addGap(32, 32, 32))
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 200));

        tblClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Class Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClassMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClass);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Class", jPanel4);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Teacher Manager"));
        jPanel7.setPreferredSize(new java.awt.Dimension(652, 338));

        jLabel9.setText("Teacher ID");

        jLabel10.setText("Teacher Name");

        jLabel11.setText("Address");

        jLabel12.setText("Email");

        jLabel13.setText("PhoneNumber");

        jLabel14.setText("Nationality");

        jLabel15.setText("Specialization");

        txtTeacherID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherIDActionPerformed(evt);
            }
        });

        btnAddTeacher.setText("Add");
        btnAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeacherActionPerformed(evt);
            }
        });

        btnEditTeacher.setText("Edit");
        btnEditTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTeacherActionPerformed(evt);
            }
        });

        btnDelTeacher.setText("Delete");
        btnDelTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelTeacherActionPerformed(evt);
            }
        });

        btnFindTeacher.setText("Find");
        btnFindTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnEditTeacher)
                                .addGap(50, 50, 50)
                                .addComponent(btnDelTeacher))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTeacherName, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                .addComponent(txtTeacherAddress)
                                .addComponent(txtTeacherEmail)
                                .addComponent(txtTeacherPhoneNumber)
                                .addComponent(txtTeacherNationality)
                                .addComponent(txtTeacherSpecialization)
                                .addComponent(txtTeacherID))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnAddTeacher)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFindTeacher)
                .addGap(147, 147, 147))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTeacherID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTeacherAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTeacherEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTeacherPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTeacherNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTeacherSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTeacher)
                    .addComponent(btnEditTeacher)
                    .addComponent(btnDelTeacher)
                    .addComponent(btnFindTeacher))
                .addGap(25, 25, 25))
        );

        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 200));

        tblTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Email", "PhoneNumber", "Nationality", "Specialization"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTeacherMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTeacher);
        if (tblTeacher.getColumnModel().getColumnCount() > 0) {
            tblTeacher.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Teacher", jPanel3);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Student Manager"));
        jPanel6.setPreferredSize(new java.awt.Dimension(652, 338));

        jLabel1.setText("Student ID");

        jLabel2.setText("Student Name");

        jLabel3.setText("Address");

        jLabel4.setText("Email");

        jLabel5.setText("PhoneNumber");

        jLabel6.setText("Nationality");

        jLabel7.setText("ClassName");

        cbxClassName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddStudent.setText("Add");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnEditStudent.setText("Edit");
        btnEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStudentActionPerformed(evt);
            }
        });

        btnDelStudent.setText("Delete");
        btnDelStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelStudentActionPerformed(evt);
            }
        });

        btnFindStudent.setText("Find");
        btnFindStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtStudentID, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                .addComponent(txtStudentName)
                                .addComponent(txtStudentAddress)
                                .addComponent(txtStudentEmail)
                                .addComponent(txtStudentPhoneNumber)
                                .addComponent(txtStudentNationality))
                            .addComponent(cbxClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnAddStudent)
                        .addGap(44, 44, 44)
                        .addComponent(btnEditStudent)
                        .addGap(48, 48, 48)
                        .addComponent(btnDelStudent)
                        .addGap(47, 47, 47)
                        .addComponent(btnFindStudent)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStudent)
                    .addComponent(btnEditStudent)
                    .addComponent(btnDelStudent)
                    .addComponent(btnFindStudent))
                .addGap(22, 22, 22))
        );

        jScrollPane3.setPreferredSize(new java.awt.Dimension(452, 200));

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Email", "PhoneNumber", "Nationality", "ClassName"
            }
        ));
        tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblStudent);
        if (tblStudent.getColumnModel().getColumnCount() > 0) {
            tblStudent.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Student", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Student
    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        String id = txtStudentID.getText();
        String name = txtStudentName.getText();
        String address = txtStudentAddress.getText();
        String email = txtStudentEmail.getText();
        String phoneNumber = txtStudentPhoneNumber.getText();
        String nationality = txtStudentNationality.getText();
        String classname = (String) cbxClassName.getSelectedItem();
        
        
        Student std = new Student(id, name, address, email, phoneNumber, nationality, classname);
        
        StudentModify.insert(std);
        
        showStudent();
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnDelStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelStudentActionPerformed
        int selectedIndex = tblStudent.getSelectedRow();
        if(selectedIndex >= 0) {
            Student std = studentList.get(selectedIndex);
            
            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this student?");
            System.out.println("option : " + option);
            
            if(option == 0) {
                StudentModify.delete(std.getId());
                
                showStudent();
            }
        }
    }//GEN-LAST:event_btnDelStudentActionPerformed

    private void btnFindStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindStudentActionPerformed
        String input = JOptionPane.showInputDialog(this, "Enter full name to search");
        if(input != null && input.length() > 0) {
            studentList = StudentModify.findByName(input);
            
            tableModel1.setRowCount(0);
        
            studentList.forEach((student) -> {
                tableModel1.addRow(new Object[] {student.getId(), 
                    student.getName(), student.getAddress(), student.getEmail(), student.getPhoneNumber(), student.getNationality(), student.getClassName()});
            });
        } else {
            showStudent();
        }
    }//GEN-LAST:event_btnFindStudentActionPerformed

    private void btnEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStudentActionPerformed
        String id = txtStudentID.getText();
        String name = txtStudentName.getText();
        String address = txtStudentAddress.getText();
        String email = txtStudentEmail.getText();
        String phoneNumber = txtStudentPhoneNumber.getText();
        String nationality = txtStudentNationality.getText();
        String classname = (String) cbxClassName.getSelectedItem();
        
        
        Student std = new Student(id, name, address, email, phoneNumber, nationality, classname);
        
        StudentModify.update(std);
        
        showStudent();
    }//GEN-LAST:event_btnEditStudentActionPerformed

    //Teacher                                                                                                                                            
    private void txtTeacherIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeacherIDActionPerformed

    private void showTeacher() {
        teacherList = TeacherModify.findAll();
        
        tableModel2.setRowCount(0);
        
        teacherList.forEach((teacher) -> {
            tableModel2.addRow(new Object[] {teacher.getId(), 
                teacher.getName(), teacher.getAddress(), teacher.getEmail(), teacher.getPhoneNumber(), teacher.getNationality(), teacher.getSpecialization()});
        });
    }
    
    private void btnAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeacherActionPerformed
        String id = txtTeacherID.getText();
        String name = txtTeacherName.getText();
        String address = txtTeacherAddress.getText();
        String email = txtTeacherEmail.getText();
        String phoneNumber = txtTeacherPhoneNumber.getText();
        String nationality = txtTeacherNationality.getText();
        String specialization = txtTeacherSpecialization.getText();
        
        
        Teacher std = new Teacher(id, name, address, email, phoneNumber, nationality, specialization);
        
        TeacherModify.insert(std);
        
        showTeacher();
    }//GEN-LAST:event_btnAddTeacherActionPerformed

    private void btnEditTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTeacherActionPerformed
        String id = txtTeacherID.getText();
        String name = txtTeacherName.getText();
        String address = txtTeacherAddress.getText();
        String email = txtTeacherEmail.getText();
        String phoneNumber = txtTeacherPhoneNumber.getText();
        String nationality = txtTeacherNationality.getText();
        String specialization = txtTeacherSpecialization.getText();
        
        
        Teacher std = new Teacher(id, name, address, email, phoneNumber, nationality, specialization);
        
        TeacherModify.update(std);
        
        showTeacher();
    }//GEN-LAST:event_btnEditTeacherActionPerformed

    private void btnDelTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelTeacherActionPerformed
        int selectedIndex = tblTeacher.getSelectedRow();
        if(selectedIndex >= 0) {
            Teacher std = teacherList.get(selectedIndex);
            
            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this teacher?");
            System.out.println("option : " + option);
            
            if(option == 0) {
                TeacherModify.delete(std.getId());
                
                showTeacher();
            }
        }
    }//GEN-LAST:event_btnDelTeacherActionPerformed

    private void btnFindTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindTeacherActionPerformed
        String input = JOptionPane.showInputDialog(this, "Enter full name to search");
        if(input != null && input.length() > 0) {
            teacherList = TeacherModify.findByName(input);
            
            tableModel2.setRowCount(0);
        
            teacherList.forEach((teacher) -> {
                tableModel2.addRow(new Object[] {teacher.getId(), 
                    teacher.getName(), teacher.getAddress(), teacher.getEmail(), teacher.getPhoneNumber(), teacher.getNationality(), teacher.getSpecialization()});
            });
        } else {
            showTeacher();
        }
    }//GEN-LAST:event_btnFindTeacherActionPerformed

    private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMouseClicked
        int row = tblStudent.getSelectedRow();
        if(row<0)
            return;
        txtStudentID.setText(tblStudent.getValueAt(row, 0).toString());
        txtStudentName.setText(tblStudent.getValueAt(row, 1).toString());
        txtStudentAddress.setText(tblStudent.getValueAt(row, 2).toString());
        txtStudentEmail.setText(tblStudent.getValueAt(row, 3).toString());
        txtStudentPhoneNumber.setText(tblStudent.getValueAt(row, 4).toString());
        txtStudentNationality.setText(tblStudent.getValueAt(row, 5).toString());
        cbxClassName.setSelectedItem(tblStudent.getValueAt(row, 6).toString());
    }//GEN-LAST:event_tblStudentMouseClicked

    private void tblTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTeacherMouseClicked
        int row = tblTeacher.getSelectedRow();
        if(row<0)
            return;
        txtTeacherID.setText(tblTeacher.getValueAt(row, 0).toString());
        txtTeacherName.setText(tblTeacher.getValueAt(row, 1).toString());
        txtTeacherAddress.setText(tblTeacher.getValueAt(row, 2).toString());
        txtTeacherEmail.setText(tblTeacher.getValueAt(row, 3).toString());
        txtTeacherPhoneNumber.setText(tblTeacher.getValueAt(row, 4).toString());
        txtTeacherNationality.setText(tblTeacher.getValueAt(row, 5).toString());
        txtTeacherSpecialization.setText(tblTeacher.getValueAt(row, 6).toString());
    }//GEN-LAST:event_tblTeacherMouseClicked
    


    //Class
    
     private void showClass() {
        classList = ClassModify.findAll();
        
        tableModel3.setRowCount(0);
        
        classList.forEach((className) -> {
            tableModel3.addRow(new Object[] {className.getClassName()});
        });
    }
    private void btnAddClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClassActionPerformed
        String className = txtClassName.getText();
        
        
        
        Class std = new Class(className);
        
        ClassModify.insert(std);
        
        showClass();
    }//GEN-LAST:event_btnAddClassActionPerformed

    private void btnDelClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelClassActionPerformed
        int selectedIndex = tblClass.getSelectedRow();
        if(selectedIndex >= 0) {
            Class std = classList.get(selectedIndex);
            
            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this class?");
            System.out.println("option : " + option);
            
            if(option == 0) {
                ClassModify.delete(std.getClassName());
                
                showClass();
            }
        }
    }//GEN-LAST:event_btnDelClassActionPerformed

    private void btnFindClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindClassActionPerformed
        String input = JOptionPane.showInputDialog(this, "Enter full name to search");
        if(input != null && input.length() > 0) {
            classList = ClassModify.findByName(input);
            
            tableModel3.setRowCount(0);
        
            classList.forEach((className) -> {
                tableModel3.addRow(new Object[] {className.getClassName()});
            });
        } else {
            showClass();
        }
    }//GEN-LAST:event_btnFindClassActionPerformed

    private void tblClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClassMouseClicked
        int row = tblClass.getSelectedRow();
        if(row<0)
            return;
        txtClassName.setText(tblClass.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tblClassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLTH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLTH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLTH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLTH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new QLTH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClass;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnAddTeacher;
    private javax.swing.JButton btnDelClass;
    private javax.swing.JButton btnDelStudent;
    private javax.swing.JButton btnDelTeacher;
    private javax.swing.JButton btnEditStudent;
    private javax.swing.JButton btnEditTeacher;
    private javax.swing.JButton btnFindClass;
    private javax.swing.JButton btnFindStudent;
    private javax.swing.JButton btnFindTeacher;
    private javax.swing.JComboBox<String> cbxClassName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblClass;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTable tblTeacher;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtStudentAddress;
    private javax.swing.JTextField txtStudentEmail;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentNationality;
    private javax.swing.JTextField txtStudentPhoneNumber;
    private javax.swing.JTextField txtTeacherAddress;
    private javax.swing.JTextField txtTeacherEmail;
    private javax.swing.JTextField txtTeacherID;
    private javax.swing.JTextField txtTeacherName;
    private javax.swing.JTextField txtTeacherNationality;
    private javax.swing.JTextField txtTeacherPhoneNumber;
    private javax.swing.JTextField txtTeacherSpecialization;
    // End of variables declaration//GEN-END:variables
}
